name: test

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "~3.11.0-0", "pypy-3.8"]
        os: [ubuntu-latest, windows-latest]
        include:
          - python: "3.7"
            tox_env: "py37"
          - python: "3.8"
            tox_env: "py38"
          - python: "3.9"
            tox_env: "py39"
          - python: "3.10"
            tox_env: "py310"
          - python: "~3.11.0-0" # see https://github.com/actions/setup-python/issues/213#issuecomment-1146676713
            tox_env: py311
          - python: "pypy-3.8"
            tox_env: "pypy3"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Cache tox environments
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ matrix.os }}-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}
      - name: Test
        run: tox -e ${{ matrix.tox_env }}
